### ISSUE TITLE
readme instructions might not work anymore?

### ISSUE THREAD

**Issue by ityonemo** [voltone/x509#33] opened 2020-02-28 19:51 UTC
Erlang/Elixir versions:

Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Interactive Elixir (1.10.1)

public_key version: 1.7.1

Issue:

following code:
```
# make your own CA
ca_key = X509.PrivateKey.new_ec(:secp256r1)
ca = X509.Certificate.self_signed(ca_key,
  "/C=US/ST=CA/L=San Francisco/O=Acme/CN=ECDSA Root CA",
  template: :root_ca)

# generate server authentications
server_key = X509.PrivateKey.new_ec(:secp256r1)
server_csr = X509.CSR.new(server_key,
  "/C=US/ST=CA/L=San Francisco/O=Acme",
  extension_request: [
    X509.Certificate.Extension.subject_alt_name(["127.0.0.1"])])

subject = X509.CSR.subject(server_csr)

server_cert = server_csr
|> X509.CSR.public_key
|> X509.Certificate.new(
  #"/C=US/ST=CA/L=San Francisco/O=Acme"
  subject, 
  ca, ca_key, extensions: [
    subject_alt_name: X509.Certificate.Extension.subject_alt_name(["127.0.0.1"])
  ]
)
```

fails, but succeeds if `subject,` line is commented out and line previous to it is uncommented, it works correctly.

specific failure:
```
** (MatchError) no match of right hand side value: {:error, {:asn1, {:badarg, [{:erlang, :element, [1, <<12, 2, 67, 65>>], []}, {:"OTP-PUB-KEY", :enc_X520StateOrProvinceName, 2, [file: 'OTP-PUB-KEY.erl', line: 14010]}, {:"OTP-PUB-KEY", :encode, 2, [file: 'OTP-PUB-KEY.erl', line: 1103]}, {:pubkey_cert_records, :transform, 2, [file: 'pubkey_cert_records.erl', line: 80]}, {:lists, :map, 2, [file: 'lists.erl', line: 1239]}, {:lists, :map, 2, [file: 'lists.erl', line: 1239]}, {:pubkey_cert_records, :transform, 2, [file: 'pubkey_cert_records.erl', line: 92]}, {:pubkey_cert_records, :encode_tbs, 1, [file: 'pubkey_cert_records.erl', line: 308]}]}}}
```

**Comment by voltone** [comment] 2020-02-29 10:14
Ah, it never worked, actually :) Thanks for the report! The issue is that some `:public_key` APIs return `:plain` ASN.1 records, while others return `:otp` variants where nested data has been decoded as well.

Fixed in v0.8.1, through c00cc0ede9c69bbada2885ad54f0112012843130

**Closed by voltone** 2020-02-29 10:14 UTC
